-- ============================================
-- Refresh Toko Table with Correct Data
-- Source: Database Toko.xlsx
-- SAFE: Does NOT delete zonas (preserves user assignments)
-- ============================================

-- Clear only toko data (not zonas)
DELETE FROM public.toko;

-- Keep existing zonas - just update/ensure they exist
INSERT INTO public.zonas (kode, nama) VALUES
('01', 'Zona 01'),
('02', 'Zona 02'),
('03A', 'Zona 03A'),
('03B', 'Zona 03B'),
('04', 'Zona 04'),
('05', 'Zona 05'),
('06A', 'Zona 06A'),
('06B', 'Zona 06B'),
('07', 'Zona 07'),
('08', 'Zona 08'),
('09', 'Zona 09'),
('10', 'Zona 10'),
('11', 'Zona 11'),
('12', 'Zona 12'),
('13', 'Zona 13'),
('14', 'Zona 14'),
('15', 'Zona 15'),
('16', 'Zona 16'),
('17', 'Zona 17')
ON CONFLICT (kode) DO UPDATE SET nama = EXCLUDED.nama;

-- Re-insert toko data - nama only (no kode field needed)
INSERT INTO public.toko (nama, zona_id) VALUES
('Mega Baja Balaraja', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Serang Timur', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Bitung', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Cipondoh', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Pasar Kemis', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Kutabumi', (SELECT id FROM public.zonas WHERE kode = '01')),
('MEGA BAJA CILEGON', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Ciruas', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Karawaci', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Bintaro', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Sawangan', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Gading Serpong', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Ciledug', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Pinang', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Cengkareng', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Joglo', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Sawangan 2', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Karang Tengah', (SELECT id FROM public.zonas WHERE kode = '02')),
('Fitrah Jaya Stainles', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Jatiwaringin', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Condet', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Harapan Indah', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Duren Sawit', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Rorotan', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium Karawang', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Granit', (SELECT id FROM public.zonas WHERE kode = '03B')),
('Mega Warna Kalimalang', (SELECT id FROM public.zonas WHERE kode = '03B')),
('Mega Baja Indonesia Cibubur', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cibubur', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Bantar Gebang', (SELECT id FROM public.zonas WHERE kode = '04')),
('Dunia Baja Komsen', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cikeas', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Pedurenan', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cimanggis', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Setu', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Dramaga', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Rangkas Bitung', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Karadenan', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Jasinga', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Stainless Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Sentul', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Parung', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Sukabumi', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Bogor', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Ciawi', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cianjur', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cipeuyeum', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cigombong', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Sukaraja', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Pelabuhan Ratu', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Garut (CV Bainit Unggul)', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Majalaya', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Soreang', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Cikalong', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Sumedang', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Cimahi', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Rancaekek', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Singaparna', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Karawang', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Kedawung - Cirebon', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Palimanan', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Cikampek', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Cirebon', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Purwakarta', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Karawang Timur', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Subang', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Rengas Dengklok', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Kuningan', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Majalengka', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Indonesia - Semarang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Brebes', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Semarang Unggaran', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Pemalang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Kudus', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Slawi', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Kendal', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Rembang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Comal', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Temanggung', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Yogyakarta', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Solo', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Magelang', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Kebumen', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Sragen', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Prambanan', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Kulon Progo', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Boyolali', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Surabaya', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Madiun', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Mojokerto', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Jember', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Malang', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Denpasar', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Kuta Bali', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Denpasar Utara', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Tulungagung', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Lampung', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Bandar Jaya', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Kotabumi', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Palembang', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Tasikmalaya', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Purwokerto', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Banjarnegara', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Wangon', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Makassar', (SELECT id FROM public.zonas WHERE kode = '13')),
('Mega Baja Gowa', (SELECT id FROM public.zonas WHERE kode = '13')),
('MEGA BAJA SEPINGGAN', (SELECT id FROM public.zonas WHERE kode = '14')),
('Mega Baja Kariangau - Balikpapan', (SELECT id FROM public.zonas WHERE kode = '14')),
('Mega Baja Samarinda', (SELECT id FROM public.zonas WHERE kode = '14')),
('Dunia Baja Kayuputih', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Jonggol', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Kaliabang', (SELECT id FROM public.zonas WHERE kode = '15')),
('Mega Baja Kalimalang', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Cibitung', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Deltamas', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Sukatani', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Pulogebang', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Bandung', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Cikarang', (SELECT id FROM public.zonas WHERE kode = '17')),
('Mega Baja Sukadami', (SELECT id FROM public.zonas WHERE kode = '17')),
('Mega Baja Cibarusah', (SELECT id FROM public.zonas WHERE kode = '17'));

-- Verify inserts
SELECT 
  z.kode,
  z.nama as zona_nama,
  COUNT(t.id) as toko_count
FROM public.zonas z
LEFT JOIN public.toko t ON t.zona_id = z.id
GROUP BY z.id, z.kode, z.nama
ORDER BY z.kode;
-- Re-insert toko data - nama only (no kode field needed)
INSERT INTO public.toko (nama, zona_id) VALUES
('Mega Baja Balaraja', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Serang Timur', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Bitung', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Cipondoh', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Pasar Kemis', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Kutabumi', (SELECT id FROM public.zonas WHERE kode = '01')),
('MEGA BAJA CILEGON', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Ciruas', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Karawaci', (SELECT id FROM public.zonas WHERE kode = '01')),
('Mega Baja Bintaro', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Sawangan', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Gading Serpong', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Ciledug', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Pinang', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Cengkareng', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Joglo', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Sawangan 2', (SELECT id FROM public.zonas WHERE kode = '02')),
('Mega Baja Karang Tengah', (SELECT id FROM public.zonas WHERE kode = '02')),
('Fitrah Jaya Stainles', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Jatiwaringin', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Condet', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Harapan Indah', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Duren Sawit', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Baja Rorotan', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium Karawang', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Aluminium Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '03A')),
('Mega Granit', (SELECT id FROM public.zonas WHERE kode = '03B')),
('Mega Warna Kalimalang', (SELECT id FROM public.zonas WHERE kode = '03B')),
('Mega Baja Indonesia Cibubur', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cibubur', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Bantar Gebang', (SELECT id FROM public.zonas WHERE kode = '04')),
('Dunia Baja Komsen', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cikeas', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Pedurenan', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Cimanggis', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Setu', (SELECT id FROM public.zonas WHERE kode = '04')),
('Mega Baja Dramaga', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Rangkas Bitung', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Karadenan', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Jasinga', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Stainless Leuwiliang', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Sentul', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Parung', (SELECT id FROM public.zonas WHERE kode = '05')),
('Mega Baja Sukabumi', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Bogor', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Ciawi', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cianjur', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cipeuyeum', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Cigombong', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Sukaraja', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Pelabuhan Ratu', (SELECT id FROM public.zonas WHERE kode = '06A')),
('Mega Baja Garut (CV Bainit Unggul)', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Majalaya', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Soreang', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Cikalong', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Sumedang', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Cimahi', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Rancaekek', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Singaparna', (SELECT id FROM public.zonas WHERE kode = '06B')),
('Mega Baja Karawang', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Kedawung - Cirebon', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Palimanan', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Cikampek', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Cirebon', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Purwakarta', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Karawang Timur', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Subang', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Rengas Dengklok', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Kuningan', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Majalengka', (SELECT id FROM public.zonas WHERE kode = '07')),
('Mega Baja Indonesia - Semarang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Brebes', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Semarang Unggaran', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Pemalang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Kudus', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Slawi', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Kendal', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Rembang', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Comal', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Temanggung', (SELECT id FROM public.zonas WHERE kode = '08')),
('Mega Baja Yogyakarta', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Solo', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Magelang', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Kebumen', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Sragen', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Prambanan', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Kulon Progo', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Boyolali', (SELECT id FROM public.zonas WHERE kode = '09')),
('Mega Baja Surabaya', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Madiun', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Mojokerto', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Jember', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Malang', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Denpasar', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Kuta Bali', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Denpasar Utara', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Tulungagung', (SELECT id FROM public.zonas WHERE kode = '10')),
('Mega Baja Lampung', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Bandar Jaya', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Kotabumi', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Palembang', (SELECT id FROM public.zonas WHERE kode = '11')),
('Mega Baja Tasikmalaya', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Purwokerto', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Banjarnegara', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Wangon', (SELECT id FROM public.zonas WHERE kode = '12')),
('Mega Baja Makassar', (SELECT id FROM public.zonas WHERE kode = '13')),
('Mega Baja Gowa', (SELECT id FROM public.zonas WHERE kode = '13')),
('MEGA BAJA SEPINGGAN', (SELECT id FROM public.zonas WHERE kode = '14')),
('Mega Baja Kariangau - Balikpapan', (SELECT id FROM public.zonas WHERE kode = '14')),
('Mega Baja Samarinda', (SELECT id FROM public.zonas WHERE kode = '14')),
('Dunia Baja Kayuputih', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Jonggol', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Kaliabang', (SELECT id FROM public.zonas WHERE kode = '15')),
('Mega Baja Kalimalang', (SELECT id FROM public.zonas WHERE kode = '15')),
('Dunia Baja Cibitung', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Deltamas', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Sukatani', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Pulogebang', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Bandung', (SELECT id FROM public.zonas WHERE kode = '16')),
('Mega Baja Cikarang', (SELECT id FROM public.zonas WHERE kode = '17')),
('Mega Baja Sukadami', (SELECT id FROM public.zonas WHERE kode = '17')),
('Mega Baja Cibarusah', (SELECT id FROM public.zonas WHERE kode = '17'));

-- Verify inserts
SELECT 
  z.kode,
  z.nama as zona_nama,
  COUNT(t.id) as toko_count
FROM public.zonas z
LEFT JOIN public.toko t ON t.zona_id = z.id
GROUP BY z.id, z.kode, z.nama
ORDER BY z.kode;
